export enum RepositoryType {
  SEARCH_REPOSITORY_LOADING = 'SEARCH_REPOSITORY_LOADING',
  SEARCH_REPOSITORY_SUCCESS = 'SEARCH_REPOSITORY_SUCCESS',
  SEARCH_REPOSITORY_ERROR = 'SEARCH_REPOSITORY_ERROR',
}
